mysite/filmblog/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostManageView

from . import views

app_name = 'filmblog'


urlpatterns = [
    path("", PostListView.as_view(), name="index"),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('tag/<slug:tag_slug>/', PostListView.as_view(), name='post_list_by_tag'),
    path('post/create/', PostCreateView.as_view(), name='post_create'),
    path('posts/manage/', PostManageView.as_view(), name='post_manage'),
    path('post/<slug:slug>/edit/', views.PostEditView.as_view(), name='post_edit'),
    path('post/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("filmblog.urls", namespace='filmblog')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/filmblog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
		     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.TextField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    preview = models.TextField(blank=True)
    original_author = models.CharField(null=True, blank=True, max_length=250)
    body = models.TextField()
    image = models.ImageField(null=True, blank=True)
    image_preview = models.ImageField(null=True, blank=True)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    objects = models.Manager()  # Менеджер по умолчанию
    published = PublishedManager()  # Собственный менеджер

    def get_absolute_url(self):
        return reverse('filmblog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])

    @property
    def image_previewURL(self):
        try:
            url = self.image_preview.url
        except:
            url = ''
        return url

mysite/filmblog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body', 'image', 'image_preview', 'preview', 'status', 'tags']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

    def clean_title(self):
        title = self.cleaned_data['title']
        if Post.objects.filter(
            title=title,
            author=self.user
        ).exists():
            raise forms.ValidationError('У вас уже есть пост с таким заголовком')
        return title

mysite/filmblog/views.py
# Django core
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.text import slugify

# Django views
from django.views.generic import (
    CreateView,
    DetailView,
    ListView,
    UpdateView
)
from django.contrib.auth.mixins import LoginRequiredMixin

# Third party
from taggit.models import Tag

# Local
from .forms import PostForm
from .models import Post


class PostListView(ListView):
    """
    Представление для отображения списка постов с фильтрацией по тегам и пагинацией

    Атрибуты:
        model (Post): Модель для получения данных
        template_name (str): Путь к шаблону index.html
        context_object_name (str): Имя переменной списка постов в шаблоне
        paginate_by (int): Количество постов на странице
    """
    model = Post
    template_name = 'filmblog/index.html'
    context_object_name = 'page_obj'
    paginate_by = 8

    def get_queryset(self):
        """
        Возвращает отфильтрованный QuerySet постов

        Returns:
            QuerySet: Опубликованные посты, отфильтрованные по тегу (если указан),
                     с предзагруженными данными автора и тегов
        """
        queryset = Post.published.all()
        tag_slug = self.kwargs.get('tag_slug')

        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[tag])

        return queryset.select_related('author').prefetch_related('tags')

    def get_context_data(self, **kwargs):
        """
        Расширяет контекст шаблона дополнительными данными

        Args:
            **kwargs: Дополнительные именованные аргументы

        Returns:
            dict: Контекст с дополнительными данными:
                - page_obj: Пагинированный список постов
                - tag: Текущий тег (если указан)
                - articles: Посты с указанным тегом
        """
        context = super().get_context_data(**kwargs)
        tag_slug = self.kwargs.get('tag_slug')

        if tag_slug:
            context['tag'] = get_object_or_404(Tag, slug=tag_slug)

        context['articles'] = Post.objects.filter(
            tags__name=context.get('tag')
        ).distinct() if context.get('tag') else None

        return context


class PostDetailView(DetailView):
    """
    Представление для отображения детальной информации о посте

    Атрибуты:
        model (Post): Модель поста
        template_name (str): Путь к шаблону детального просмотра
        context_object_name (str): Имя переменной поста в шаблоне
    """
    model = Post
    template_name = 'filmblog/single-standard.html'
    context_object_name = 'post'

    def get_object(self):
        """
        Получает конкретный пост по параметрам URL

        Returns:
            Post: Опубликованный пост с указанными параметрами или 404

        Raises:
            Http404: Если пост не найден
        """
        return get_object_or_404(
            Post,
            slug=self.kwargs['post'],
            status='published',
            publish__year=self.kwargs['year'],
            publish__month=self.kwargs['month'],
            publish__day=self.kwargs['day']
        )

    def get_context_data(self, **kwargs):
        """
        Расширяет контекст шаблона навигационными данными

        Args:
            **kwargs: Дополнительные именованные аргументы

        Returns:
            dict: Контекст с дополнительными данными:
                - post: Текущий пост
                - prev_post: Предыдущий пост
                - next_post: Следующий пост
        """
        context = super().get_context_data(**kwargs)
        post = self.get_object()

        context.update({
            'prev_post': self._get_adjacent_post(post, is_next=False),
            'next_post': self._get_adjacent_post(post, is_next=True)
        })

        return context

    def _get_adjacent_post(self, post, is_next=True):
        """
        Получает следующий или предыдущий пост относительно текущего

        Args:
            post (Post): Текущий пост
            is_next (bool): True для следующего, False для предыдущего

        Returns:
            Post|None: Соседний опубликованный пост или None если не существует
        """
        try:
            if is_next:
                return post.get_next_by_publish(status='published')
            return post.get_previous_by_publish(status='published')
        except Post.DoesNotExist:
            return None

class SearchResultsView(ListView):
    """
    Представление для поиска постов по заголовку

    Атрибуты:
        model (Post): Модель для поиска
        template_name (str): Путь к шаблону результатов
        context_object_name (str): Имя переменной с результатами в контексте
        paginate_by (int): Количество результатов на странице
    """
    model = Post
    template_name = 'filmblog/search_results.html'
    context_object_name = 'results'
    paginate_by = 8

    def get_queryset(self):
        """
        Возвращает отфильтрованный QuerySet на основе поискового запроса

        Returns:
            QuerySet: Отфильтрованные посты или пустой QuerySet
        """
        query = self.request.GET.get('query', '')
        if query:
            return Post.objects.filter(
                Q(title__icontains=query) |
                Q(body__icontains=query) |
                Q(preview__icontains=query)
            ).select_related('author').prefetch_related('tags')
        return Post.objects.none()

    def get_context_data(self, **kwargs):
        """
        Добавляет поисковый запрос в контекст шаблона
        """
        context = super().get_context_data(**kwargs)
        context['query'] = self.request.GET.get('query', '')
        return context


class PostCreateView(LoginRequiredMixin, CreateView):
    """
    Представление для создания новых постов

    Атрибуты:
        model (Post): Модель поста
        template_name (str): Путь к шаблону создания
        form_class (PostForm): Форма для создания поста
        success_url (str): URL для перенаправления после успешного создания
    """
    model = Post
    template_name = 'filmblog/post_create.html'
    form_class = PostForm
    success_url = reverse_lazy('filmblog:index')

    def get_form_kwargs(self):
        """Передает дополнительные аргументы в форму"""
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """
        Обработка валидной формы

        Args:
            form: Валидированная форма

        Returns:
            HttpResponse: Ответ с перенаправлением
        """
        form.instance.author = self.request.user
        form.instance.original_author = self.request.user.username
        form.instance.slug = slugify(form.cleaned_data['title'])

        return super().form_valid(form)


    def get_success_url(self):
        """Получает URL для перенаправления после создания поста"""
        return self.object.get_absolute_url()


class PostManageView(LoginRequiredMixin, ListView):
    """
    Представление для управления постами

    Атрибуты:
        model (Post): Модель поста
        template_name (str): Путь к шаблону управления постами
        context_object_name (str): Имя переменной списка постов в контексте
        paginate_by (int): Количество постов на странице
    """
    model = Post
    template_name = 'filmblog/post_manage.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        """
        Получает отсортированный и оптимизированный QuerySet постов

        Returns:
            QuerySet: Посты с предзагруженными связанными данными
        """
        return Post.objects.select_related('author') \
            .prefetch_related('tags') \
            .order_by('-created')

    def get_context_data(self, **kwargs):
        """Добавляет дополнительный контекст"""
        context = super().get_context_data(**kwargs)
        context.update({
            'total_posts': Post.objects.count(),
            'published_posts': Post.published.count(),
            'draft_posts': Post.objects.filter(status='draft').count()
        })
        return context

    def get_queryset_by_status(self, status):
        """
        Фильтрует посты по статусу

        Args:
            status (str): Статус постов ('published' или 'draft')
        """
        queryset = self.get_queryset()
        return queryset.filter(status=status)


class PostEditView(LoginRequiredMixin, UpdateView):
    """
    Представление для редактирования постов

    Атрибуты:
        model (Post): Модель поста
        template_name (str): Путь к шаблону редактирования
        form_class (PostForm): Форма для редактирования поста
    """
    model = Post
    template_name = 'filmblog/post_edit.html'
    form_class = PostForm

    def get_form_kwargs(self):
        """Передает дополнительные аргументы в форму"""
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        """
        Обработка валидной формы

        Args:
            form: Валидированная форма

        Returns:
            HttpResponse: Ответ с перенаправлением
        """
        if form.has_changed():
            form.instance.updated = timezone.now()
            form.instance.slug = slugify(form.cleaned_data['title'])
        return super().form_valid(form)

    def get_queryset(self):
        """Оптимизация запросов к БД"""
        return Post.objects.select_related('author').prefetch_related('tags')

    def get_success_url(self):
        """URL для перенаправления после успешного редактирования"""
        messages.success(self.request, 'Пост успешно обновлен')
        return reverse_lazy('filmblog:post_manage')

    def dispatch(self, request, *args, **kwargs):

mysite/filmblog/templates/filmblog/base.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}D76 is art{% endblock %}</title>
    <meta content="" name="description">
    <meta content="" name="author">
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <link href="{% static 'filmblog/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'filmblog/css/vendor.css' %}" rel="stylesheet">
    <link href="{% static 'filmblog/css/main.css' %}" rel="stylesheet">
    {% block extra_css %}{% endblock %}

    <script src="{% static 'filmblog/js/modernizr.js' %}"></script>

    <link href="{% static 'filmblog/apple-touch-icon.png' %}" rel="apple-touch-icon" sizes="180x180">
    <link href="{% static 'filmblog/favicon-32x32.png' %}" rel="icon" sizes="32x32" type="image/png">
    <link href="{% static 'filmblog/favicon-16x16.png' %}" rel="icon" sizes="16x16" type="image/png">
    <link href="{% static 'filmblog/site.webmanifest' %}" rel="manifest">
</head>

<body>
    <div id="preloader">
        <div class="dots-fade" id="loader">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <div class="s-wrap site-wrapper" id="top">
        <header class="s-header">
            <div class="header__top">
                <div class="header__logo">
                    <a class="site-logo" href="{% url 'filmblog:index' %}">
                        <img alt="Homepage" src="{% static 'filmblog/images/logo.svg' %}">
                    </a>
                </div>

                <div class="header__search">
                    <form action="{% url 'filmblog:search_results' %}" class="header__search-form" method="get" role="search">
                        <label>
                            <span class="hide-content">Поиск:</span>
                            <input autocomplete="off" class="header__search-field" name="query" placeholder="Ключевые слова" type="search">
                        </label>
                        <input class="header__search-submit" type="submit" value="Search">
                    </form>
                </div>

                <a class="header__search-trigger" href="#0"></a>
                <a class="header__menu-toggle" href="#0"><span>Menu</span></a>
            </div>

            <nav class="header__nav-wrap">
                <ul class="header__nav">
                    <li class="current"><a href="{% url 'filmblog:index' %}">Главная</a></li>
                    <li class="has-children">
                        <a href="#0">Категории</a>
                        <ul class="sub-menu">
                            <li><a href="{% url 'filmblog:post_list_by_tag' 'film' %}">Пленка</a></li>
                            <li><a href="{% url 'filmblog:post_list_by_tag' 'author' %}">Автор</a></li>
                            <li><a href="{% url 'filmblog:post_list_by_tag' 'bw' %}">Черно-белое</a></li>
                        </ul>
                    </li>
                </ul>

                <ul class="header__social">
                    <li class="ss-facebook">
                        <a href="https://facebook.com/"><span class="screen-reader-text">Facebook</span></a>
                    </li>
                    <li class="ss-twitter">
                        <a href="#0"><span class="screen-reader-text">Twitter</span></a>
                    </li>
                    <li class="ss-dribbble">
                        <a href="#0"><span class="screen-reader-text">Dribbble</span></a>
                    </li>
                    <li class="ss-pinterest">
                        <a href="#0"><span class="screen-reader-text">Behance</span></a>
                    </li>
                </ul>
            </nav>
        </header>

        <div class="s-content">
            {% block content %}{% endblock %}
        </div>

        <footer class="s-footer">
            <div class="row">
                <div class="column large-full footer__content">
                    <div class="footer__copyright">
                    </div>
                </div>
            </div>
            <div class="go-top">
                <a class="smoothscroll" href="#top" title="Вверх"></a>
            </div>
        </footer>

    </div>

    <script src="{% static 'filmblog/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'filmblog/js/plugins.js' %}"></script>
    <script src="{% static 'filmblog/js/main.js' %}"></script>
    {% block extra_js %}{% endblock %}

</body>
</html>

mysite/filmblog/templates/filmblog/post_manage.html
{% extends 'filmblog/base.html' %}

{% block title %}Управление постами{% endblock %}

{% block content %}
<div class="s-content">
    <div class="row">
        <div class="column large-12">
            <article class="s-content__entry">
                <div class="s-content__entry-header">
                    <h1 class="s-content__title">Управление постами</h1>
                </div>

                <div class="s-content__primary">
                    <div class="entry__table">
                        <table class="full-width">
                            <thead>
                                <tr>
                                    <th>Заголовок</th>
                                    <th>Статус</th>
                                    <th>Дата создания</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for post in posts %}
                                <tr>
                                    <td>{{ post.title }}</td>
                                    <td>{{ post.get_status_display }}</td>
                                    <td>{{ post.created|date:"d.m.Y" }}</td>
                                    <td>
                                        <a href="{{ post.get_absolute_url }}" class="btn btn--small">Просмотр</a>
                                        <a href="{% url 'filmblog:post_edit' post.slug %}" class="btn btn--small btn--primary">Редактировать</a>
                                        <a href="{% url 'filmblog:post_delete' post.slug %}" class="btn btn--small btn--danger"
                                           onclick="return confirm('Вы уверены, что хотите удалить этот пост?')">Удалить</a>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>

                    {% if is_paginated %}
                    <nav class="pgn">
                        <ul>
                            {% if page_obj.has_previous %}
                            <li><a class="pgn__prev" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
                            {% endif %}

                            {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                            <li><span class="pgn__num current">{{ num }}</span></li>
                            {% else %}
                            <li><a class="pgn__num" href="?page={{ num }}">{{ num }}</a></li>
                            {% endif %}
                            {% endfor %}

                            {% if page_obj.has_next %}
                            <li><a class="pgn__next" href="?page={{ page_obj.next_page_number }}">Next</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                    {% endif %}

                    <div class="entry__buttons">
                        <a href="{% url 'filmblog:post_create' %}" class="btn btn--primary full-width">Создать новый пост</a>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>
{% endblock %}

{% block extra_css %}
<style>
    .entry__table table {
        width: 100%;
        border-collapse: collapse;
        margin-bottom: 2rem;
    }
    .entry__table th,
    .entry__table td {
        padding: 1rem;
        text-align: left;
        border-bottom: 1px solid #ddd;
    }
    .btn--danger {
        background: #dc3545;
        color: white;
    }
    .btn--small {
        padding: 0.5rem 1rem;
        font-size: 1.4rem;
        margin-right: 0.5rem;
    }
</style>
{% endblock %}

mysite/filmblog/templates/filmblog/search_results.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
<head>

    <!--- basic page needs
    ================================================== -->
    <meta charset="utf-8">
    <title>D76 is art</title>
    <meta content="" name="description">
    <meta content="" name="author">

    <!-- mobile specific metas
    ================================================== -->
    <meta content="width=device-width, initial-scale=1" name="viewport">

    <!-- CSS
    ================================================== -->
    <link href="{% static 'filmblog/css/base.css' %}" rel="stylesheet">
    <link href="{% static 'filmblog/css/vendor.css' %}" rel="stylesheet">
    <link href="{% static 'filmblog/css/main.css' %}" rel="stylesheet">

    <!-- script
    ================================================== -->
    <script src="{% static 'filmblog/js/modernizr.js' %}"></script>

    <!-- favicons
    ================================================== -->
    <link href="{% static 'filmblog/apple-touch-icon.png' %}" rel="apple-touch-icon" sizes="180x180">
    <link href="{% static 'filmblog/favicon-32x32.png' %}" rel="icon" sizes="32x32" type="image/png">
    <link href="{% static 'filmblog/favicon-16x16.png' %}" rel="icon" sizes="16x16" type="image/png">
    <link href="{% static 'filmblog/site.webmanifest' %}" rel="manifest">

</head>

<body>

<!-- preloader
================================================== -->
<div id="preloader">
    <div class="dots-fade" id="loader">
        <div></div>
        <div></div>
        <div></div>
    </div>
</div>

<div class="s-wrap site-wrapper" id="top">

    <!-- site header
    ================================================== -->
    <header class="s-header">

        <div class="header__top">
            <div class="header__logo">
                <a class="site-logo" href="http://127.0.0.1:8000/">
                    <img alt="Homepage" src="{% static 'filmblog/images/logo.svg' %}">
                </a>
            </div>

            <div class="header__search">

                <form action="{% url 'filmblog:search_results' %}" class="header__search-form" method="get"
                      role="search">
                    <label>
                        <span class="hide-content">Search for:</span>
                        <input autocomplete="off" class="header__search-field" name="query" placeholder="Ключевые слова"
                               title="Search for:" type="search" value="">
                    </label>
                    <input class="header__search-submit" type="submit" value="Search">
                </form>


            </div>  <!-- end header__search -->

            <!-- toggles -->
            <a class="header__search-trigger" href="#0"></a>
            <a class="header__menu-toggle" href="#0"><span>Menu</span></a>

        </div> <!-- end header__top -->

        <nav class="header__nav-wrap">

            <ul class="header__nav">
                <li class="current"><a href="ihttp://127.0.0.1:8000/" title="">Главная</a></li>
                <li class="has-children">
                    <a href="#0" title="">Категории</a>
                    <ul class="sub-menu">
                        <!--
                    <li><a href="category.html">Lifestyle</a></li>
                    <li><a href="category.html">Health</a></li>
                    <li><a href="category.html">Family</a></li>
                    <li><a href="category.html">Management</a></li>
                    <li><a href="category.html">Travel</a></li>
                    <li><a href="category.html">Work</a></li>
                    </ul>
                </li>
                <li class="has-children">
                    <a href="#0" title="">Blog Posts</a>
                    <ul class="sub-menu">
                    <li><a href="single-video.html">Video Post</a></li>
                    <li><a href="single-audio.html">Audio Post</a></li>
                    <li><a href="single-gallery.html">Gallery Post</a></li>
                    <li><a href="single-standard.html">Standard Post</a></li>
                    </ul>
                </li>
                <li><a href="styles.html" title="">Styles</a></li>
                <li><a href="page-about.html" title="">About</a></li>
                <li><a href="page-contact.html" title="">Contact</a></li>
                 -->
                    </ul> <!-- end header__nav -->

                    <ul class="header__social">
                        <li class="ss-facebook">
                            <a href="https://facebook.com/">
                                <span class="screen-reader-text">Facebook</span>
                            </a>
                        </li>
                        <li class="ss-twitter">
                            <a href="#0">
                                <span class="screen-reader-text">Twitter</span>
                            </a>
                        </li>
                        <li class="ss-dribbble">
                            <a href="#0">
                                <span class="screen-reader-text">Dribbble</span>
                            </a>
                        </li>
                        <li class="ss-pinterest">
                            <a href="#0">
                                <span class="screen-reader-text">Behance</span>
                            </a>
                        </li>
                    </ul>

        </nav> <!-- end header__nav-wrap -->


    </header> <!-- end s-header -->

    <div class="s-content">

        <div class="masonry-wrap">
            {% if results %}
            <div class="masonry">

                <div class="grid-sizer"></div>
                {% for post in results %}

                <article class="masonry__brick entry format-standard animate-this">
                    <!-- end article22222222222222222222222222222222222222222222222222222222222222 -->

                    <div class="entry__thumb">
                        <a class="entry__thumb-link" href="{{ post.get_absolute_url }}">
                            <img alt="" src="{{ post.image_previewURL }}">
                        </a>
                    </div>

                    <div class="entry__text">
                        <div class="entry__header">

                            <h2 class="entry__title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                            <div class="entry__meta">
                                    <span class="entry__meta-cat">
                                        #
                                             {% for tag in post.tags.all %}
                                                <a href="{% url 'filmblog:post_list_by_tag' tag.slug %}">
                                                    {{ tag.name }}
                                                 </a>
                                                {% if not forloop.last %}{% endif %}
                                              {% endfor %}
                                    </span>
                            </div>

                        </div>
                        <div class="entry__excerpt">
                            <p>
                                {{ post.preview|truncatewords:30|linebreaks }}
                            </p>
                            <span class="entry__meta-date">
                                    <b><br>Автор: {{ post.original_author }}</b>
                                </span>
                        </div>
                    </div>

                </article> <!-- end article22222222222222222222222222222222222222222222222222222222222222 -->
                {% endfor %}
            </div>
            {% else %}
            {% if query %}
            <p>No results found.</p>
            {% else %}
            <p>No search query provided.</p>
            {% endif %}
            {% endif %}
        </div>
    </div> <!-- end masonry -->

</div> <!-- end masonry-wrap -->


<!-- Java Script
================================================== -->
<script src="{% static 'filmblog/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'filmblog/js/plugins.js' %}"></script>
<script src="{% static 'filmblog/js/main.js' %}"></script>

</body>